import React, { useMemo } from "react";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";

import {
  Alert,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

import { useUser } from "../context/UserContext";
import { useTransactions } from "../context/TransactionContext";
import { usePayments } from "../context/PaymentContext";
import { useDeadlines } from "../context/DeadlineContext";

export default function ComplianceCertificateScreen() {
  const { user } = useUser();

  const { transactions } =
    useTransactions();

  const { payments } =
    usePayments();

  const { deadlines } =
    useDeadlines();

  const currentYear =
    new Date().getFullYear();

  const taxYear = `${currentYear - 1}/${currentYear}`;

  const issueDate =
    new Date().toLocaleDateString();

  const validFrom =
    new Date().toLocaleDateString();

  const validUntil = new Date(
    currentYear,
    11,
    31
  ).toLocaleDateString();

  const certificateNumber =
    useMemo(() => {
      const nameLength = user?.label?.length || 0;
      return `TCC-${currentYear}-${String(
        nameLength * currentYear
      ).slice(-5)}`;
    }, [user?.label, currentYear]);

  const tin = useMemo(() => {
    return `C${String(
      (user?.tin ?? "")
        .replace(/\D/g, "")
        .padEnd(10, "0")
    ).substring(0, 10)}`;
  }, [user?.tin]);

  const outstandingDeadlines =
    deadlines.filter(
      (deadline) =>
        !deadline.completed
    );

  const totalPayments =
    payments.reduce(
      (sum, payment) =>
        payment.status === "Paid"
          ? sum + payment.amount
          : sum,
      0
    );

  const isCompliant =
    outstandingDeadlines.length === 0 &&
    transactions.length > 0 &&
    totalPayments > 0;

  const previousCertificates =
    useMemo(() => {
      return [
        {
          id: `TCC-${currentYear - 1}-0001`,
          year: `${currentYear - 2}/${
            currentYear - 1
          }`,
        },

        {
          id: `TCC-${currentYear - 2}-0002`,
          year: `${currentYear - 3}/${
            currentYear - 2
          }`,
        },
      ];
    }, [currentYear]);

  const downloadCertificate = async () => {
    try {
      const html = `
        <html>
          <body>
            <h1>GHANA REVENUE AUTHORITY</h1>

            <h2>Tax Compliance Certificate</h2>

            <hr />

            <p>
              <strong>Taxpayer Name:</strong>
              ${user?.label || "User"}
            </p>

            <p>
              <strong>TIN:</strong>
              ${tin}
            </p>

            <p>
              <strong>Certificate Number:</strong>
              ${certificateNumber}
            </p>

            <p>
              <strong>Issue Date:</strong>
              ${issueDate}
            </p>

            <p>
              <strong>Valid From:</strong>
              ${validFrom}
            </p>

            <p>
              <strong>Valid Until:</strong>
              ${validUntil}
            </p>

            <p>
              <strong>Tax Year:</strong>
              ${taxYear}
            </p>

            <p>
              <strong>Status:</strong>
              ${
                isCompliant
                  ? "VALID"
                  : "NOT VALID"
              }
            </p>

            <br />

            <p>
              This certificate was electronically generated by TaxPadi.
            </p>
          </body>
        </html>
      `;

      const { uri } =
        await Print.printToFileAsync({
          html,
        });

      if (
        await Sharing.isAvailableAsync()
      ) {
        await Sharing.shareAsync(uri);
      } else {
        Alert.alert(
          "PDF Created",
          `Saved to: ${uri}`
        );
      }
    } catch (error) {
      console.log(error);

      Alert.alert(
        "Error",
        "Unable to generate certificate."
      );
    }
  };

  const shareCertificate =
    async () => {
      try {
        await Share.share({
          message: `Tax Compliance Certificate\n\nTaxpayer: ${
            user?.label || "User"
          }\nCertificate No: ${certificateNumber}\nStatus: ${
            isCompliant
              ? "VALID"
              : "NOT VALID"
          }`,
        });
      } catch {
        Alert.alert(
          "Error",
          "Unable to share certificate."
        );
      }
    };

  const requestUpdate = () => {
    if (isCompliant) {
      Alert.alert(
        "Certificate Updated",
        "Your compliance certificate is already up to date."
      );

      return;
    }

    Alert.alert(
      "Outstanding Requirements",
      `You still have ${outstandingDeadlines.length} outstanding filing requirement(s).`
    );
  };

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={{
        paddingBottom: 50,
      }}
      showsVerticalScrollIndicator={
        false
      }
    >
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() =>
            router.back()
          }
        >
          <Ionicons
            name="arrow-back"
            size={24}
            color="#111827"
          />
        </TouchableOpacity>

        <Text style={styles.title}>
          Compliance Certificate
        </Text>
      </View>

      <View
        style={styles.certificateCard}
      >
        <View style={styles.graCircle}>
          <Text style={styles.graText}>
            GRA
          </Text>
        </View>

        <Text style={styles.authority}>
          GHANA REVENUE AUTHORITY
        </Text>

        <Text
          style={
            styles.certificateTitle
          }
        >
          Tax Compliance Certificate
        </Text>

        <View style={styles.divider} />

        <View
          style={styles.detailsRow}
        >
          <View>
            <Text style={styles.label}>
              Taxpayer Name
            </Text>

            <Text style={styles.value}>
              {user?.label || "User"}
            </Text>

            <Text
              style={[
                styles.label,
                {
                  marginTop: 12,
                },
              ]}
            >
              Valid From
            </Text>

            <Text style={styles.value}>
              {validFrom}
            </Text>

            <Text
              style={[
                styles.label,
                {
                  marginTop: 12,
                },
              ]}
            >
              Issue Date
            </Text>

            <Text style={styles.value}>
              {issueDate}
            </Text>
          </View>

          <View>
            <Text style={styles.label}>
              TIN
            </Text>

            <Text style={styles.value}>
              {tin}
            </Text>

            <Text
              style={[
                styles.label,
                {
                  marginTop: 12,
                },
              ]}
            >
              Valid Until
            </Text>

            <Text style={styles.value}>
              {validUntil}
            </Text>
          </View>
        </View>

        <Text
          style={[
            styles.validText,
            {
              color:
                isCompliant
                  ? "#34A853"
                  : "#EA4335",
            },
          ]}
        >
          {isCompliant
            ? "✓ VALID"
            : "✕ NOT VALID"}
        </Text>
      </View>

      <View style={styles.verifyCard}>
        <View
          style={styles.qrPlaceholder}
        >
          <Ionicons
            name="qr-code-outline"
            size={80}
            color="#6B7280"
          />
        </View>

        <View style={{ flex: 1 }}>
          <Text style={styles.label}>
            Certificate No.
          </Text>

          <Text style={styles.value}>
            {certificateNumber}
          </Text>

          <Text
            style={[
              styles.label,
              { marginTop: 10 },
            ]}
          >
            Filing Status
          </Text>

          <Text style={styles.value}>
            {outstandingDeadlines.length ===
            0
              ? "All Returns Filed"
              : `${outstandingDeadlines.length} Outstanding`}
          </Text>

          <Text
            style={[
              styles.label,
              { marginTop: 10 },
            ]}
          >
            Tax Year
          </Text>

          <Text style={styles.value}>
            {taxYear}
          </Text>
        </View>
      </View>

      <Text style={styles.scanText}>
        Scan to verify
      </Text>

      <View style={styles.buttonRow}>
        <TouchableOpacity
          style={
            styles.secondaryButton
          }
          onPress={
            downloadCertificate
          }
        >
          <Ionicons
            name="download-outline"
            size={18}
            color="#111827"
          />

          <Text
            style={
              styles.secondaryText
            }
          >
            Download PDF
          </Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.primaryButton}
          onPress={
            shareCertificate
          }
        >
          <Ionicons
            name="share-outline"
            size={18}
            color="#FFFFFF"
          />

          <Text
            style={styles.primaryText}
          >
            Share
          </Text>
        </TouchableOpacity>
      </View>

      <TouchableOpacity
        style={styles.requestCard}
        onPress={requestUpdate}
      >
        <View>
          <Text
            style={
              styles.requestTitle
            }
          >
            Request Updated
            Certificate
          </Text>

          <Text
            style={
              styles.requestSubtitle
            }
          >
            Refresh your latest
            compliance status
          </Text>
        </View>

        <Ionicons
          name="chevron-forward"
          size={20}
          color="#9CA3AF"
        />
      </TouchableOpacity>

      <Text style={styles.sectionTitle}>
        PREVIOUS CERTIFICATES
      </Text>

      {previousCertificates.map(
        (item) => (
          <View
            key={item.id}
            style={styles.previousCard}
          >
            <View>
              <Text
                style={
                  styles.previousId
                }
              >
                {item.id}
              </Text>

              <Text
                style={
                  styles.previousYear
                }
              >
                {item.year}
              </Text>
            </View>

            <View
              style={
                styles.previousRight
              }
            >
              <Text
                style={
                  styles.validSmall
                }
              >
                ✓ Valid
              </Text>

              <TouchableOpacity
                onPress={
                  downloadCertificate
                }
              >
                <Text
                  style={
                    styles.downloadNow
                  }
                >
                  Download Now
                </Text>
              </TouchableOpacity>
            </View>
          </View>
        )
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor:
      "#FAFAFA",
    paddingHorizontal: 20,
    paddingTop: 55,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },

  title: {
    fontSize: 28,
    marginLeft: 10,
    color: "#111827",
    fontFamily:
      "Inter_700Bold",
    flex: 1,
  },

  certificateCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
  },

  graCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor:
      "#FCE8E6",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },

  graText: {
    color: "#C44736",
    fontFamily:
      "Inter_600SemiBold",
  },

  authority: {
    textAlign: "center",
    marginTop: 14,
    fontSize: 11,
    color: "#6B7280",
  },

  certificateTitle: {
    textAlign: "center",
    color: "#C44736",
    fontSize: 18,
    fontFamily:
      "Inter_700Bold",
    marginTop: 6,
  },

  divider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 20,
  },

  detailsRow: {
    flexDirection: "row",
    justifyContent:
      "space-between",
  },

  label: {
    fontSize: 11,
    color: "#9CA3AF",
  },

  value: {
    color: "#111827",
    fontFamily:
      "Inter_600SemiBold",
  },

  validText: {
    textAlign: "right",
    marginTop: 18,
    fontFamily:
      "Inter_700Bold",
  },

  verifyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 18,
    flexDirection: "row",
    marginBottom: 8,
  },

  qrPlaceholder: {
    marginRight: 18,
    justifyContent: "center",
  },

  scanText: {
    textAlign: "center",
    color: "#C44736",
    marginBottom: 20,
    fontSize: 12,
  },

  buttonRow: {
    flexDirection: "row",
    justifyContent:
      "space-between",
    marginBottom: 20,
  },

  secondaryButton: {
    width: "48%",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },

  secondaryText: {
    marginLeft: 8,
    fontFamily:
      "Inter_600SemiBold",
  },

  primaryButton: {
    width: "48%",
    backgroundColor: "#C44736",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },

  primaryText: {
    color: "#FFFFFF",
    marginLeft: 8,
    fontFamily:
      "Inter_600SemiBold",
  },

  requestCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 18,
    flexDirection: "row",
    justifyContent:
      "space-between",
    alignItems: "center",
    marginBottom: 24,
  },

  requestTitle: {
    color: "#111827",
    fontFamily:
      "Inter_600SemiBold",
  },

  requestSubtitle: {
    color: "#6B7280",
    marginTop: 4,
    fontSize: 12,
  },

  sectionTitle: {
    color: "#C44736",
    fontSize: 11,
    marginBottom: 12,
    fontFamily:
      "Inter_600SemiBold",
  },

  previousCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 18,
    flexDirection: "row",
    justifyContent:
      "space-between",
    marginBottom: 12,
  },

  previousId: {
    color: "#111827",
    fontFamily:
      "Inter_600SemiBold",
  },

  previousYear: {
    color: "#6B7280",
    marginTop: 4,
    fontSize: 12,
  },

  previousRight: {
    alignItems: "flex-end",
  },

  validSmall: {
    color: "#34A853",
    fontSize: 12,
  },

  downloadNow: {
    color: "#C44736",
    marginTop: 6,
    fontSize: 12,
    fontFamily:
      "Inter_600SemiBold",
  },
});