import React from "react";
import { Ionicons } from "@expo/vector-icons";
import * as Print from "expo-print";
import { router } from "expo-router";
import * as Sharing from "expo-sharing";
import {
  Alert,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

import { useTaxReturns } from "../context/TaxReturnsContext";
import { generateTaxReturn } from "@/services/taxReturns.service";
import Card from "../components/Card";

export default function TaxReturnsScreen() {
  const {
    currentReturnFiled,
    filingSteps,
    previousReturns,
    toggleStep,
  } = useTaxReturns();

  const currentYear = new Date().getFullYear();

  const currentTaxYear = `FY ${currentYear}/${currentYear + 1}`;

  const dueDate = `Apr 30, ${currentYear + 1}`;

  const allStepsCompleted = filingSteps.every((step) => step.completed);

  const handleFileReturn = async () => {
    if (currentReturnFiled) {
      Alert.alert(
        "Already Filed",
        "You have already filed this year's return."
      );
      return;
    }

    if (!allStepsCompleted) {
      Alert.alert(
        "Incomplete Filing",
        "Please complete all filing steps before submitting your return."
      );
      return;
    }

    try {
      const generated = await generateTaxReturn(
        "INCOME_TAX",
        currentYear,
        new Date().getMonth() + 1
      );

      const returnId = generated.data.return_id;

      router.push({
        pathname: "/tax-return-review",
        params: {
          returnId,
        },
      });
    } catch (error) {
      console.log(error);

      Alert.alert(
        "Error",
        "Unable to submit tax return."
      );
    }
  };

  const handleDownload = async (taxYear: string, filedDate: string) => {
    try {
      const html = `
        <html>
          <body style="font-family: Arial; padding: 30px;">
            <h1 style="color:#C44736;">
              TaxPadi Tax Return
            </h1>

            <hr />

            <h2>Return Details</h2>

            <p>
              <strong>Tax Year:</strong>
              ${taxYear}
            </p>

            <p>
              <strong>Status:</strong>
              Filed
            </p>

            <p>
              <strong>Filed Date:</strong>
              ${new Date(filedDate).toLocaleDateString()}
            </p>

            <p>
              <strong>Generated:</strong>
              ${new Date().toLocaleString()}
            </p>

            <br />

            <h3>
              Filing Steps Completed
            </h3>

            <ul>
              ${filingSteps.map((step) => `<li>${step.title}</li>`).join("")}
            </ul>

            <br />

            <p>
              This document was generated by TaxPadi.
            </p>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri);
      } else {
        Alert.alert("Download Complete", `PDF saved to:\n${uri}`);
      }
    } catch (error) {
      console.log(error);
      Alert.alert("Error", "Failed to generate PDF.");
    }
  };

  return (
    <ScrollView
      style={styles.container}
      showsVerticalScrollIndicator={false}
      contentContainerStyle={{
        paddingBottom: 120,
      }}
    >
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Ionicons name="chevron-back" size={26} color="#111827" />
        </TouchableOpacity>

        <Text style={styles.title}>Tax Returns</Text>
      </View>

      <Text style={styles.subtitle}>
        File your annual tax returns and access previous submissions.
      </Text>

      {/* Current Return */}
      <View style={styles.returnCard}>
        <View style={styles.returnHeader}>
          <View style={styles.returnIcon}>
            <Ionicons name="document-text-outline" size={30} color="#FFFFFF" />
          </View>

          <View style={{ flex: 1 }}>
            <Text style={styles.taxYear}>{currentTaxYear}</Text>
            <Text style={styles.returnTitle}>Annual Income Tax Return</Text>
          </View>
        </View>

        <View style={styles.row}>
          <View
            style={[
              styles.statusBadge,
              currentReturnFiled && {
                backgroundColor: "#DCFCE7",
              },
            ]}
          >
            <Text
              style={[
                styles.statusText,
                currentReturnFiled && {
                  color: "#15803D",
                },
              ]}
            >
              {currentReturnFiled ? "Filed" : "Not Filed"}
            </Text>
          </View>

          <Text style={styles.dueDate}>Due: {dueDate}</Text>
        </View>
      </View>

      {/* File Button */}
      <TouchableOpacity
        style={[
          styles.fileButton,
          currentReturnFiled && {
            backgroundColor: "#9CA3AF",
          },
        ]}
        disabled={currentReturnFiled}
        onPress={handleFileReturn}
      >
        <Text style={styles.fileButtonText}>
          {currentReturnFiled ? "Return Filed" : "File Return Now"}
        </Text>
      </TouchableOpacity>

      {/* Filing Steps */}
      <Text style={styles.sectionLabel}>FILING STEPS</Text>

      <View style={styles.stepsCard}>
        {filingSteps.map((item, index) => {
          const isLastItem = index === filingSteps.length - 1;

          return (
            <TouchableOpacity
              key={item.step}
              style={[styles.stepRow, !isLastItem && styles.stepDivider]}
              activeOpacity={0.8}
              onPress={() => toggleStep(item.step)}
            >
              <View
                style={[
                  styles.stepCircle,
                  item.completed && styles.completedCircle,
                ]}
              >
                {item.completed ? (
                  <Ionicons name="checkmark" size={14} color="#FFFFFF" />
                ) : (
                  <Text style={styles.stepNumber}>{item.step}</Text>
                )}
              </View>

              <Text style={styles.stepTitle}>{item.title}</Text>

              {item.completed ? (
                <View style={styles.greenBadge}>
                  <Text style={styles.badgeText}>Completed</Text>
                </View>
              ) : (
                <View style={styles.grayBadge}>
                  <Text style={styles.grayBadgeText}>Pending</Text>
                </View>
              )}
            </TouchableOpacity>
          );
        })}
      </View>

      {/* Previous Returns */}
      <Text style={styles.sectionLabel}>PREVIOUS RETURNS</Text>

      {previousReturns.length === 0 ? (
        <Card style={styles.emptyStateCard}>
          <Ionicons
            name="document-text-outline"
            size={48}
            color="#9CA3AF"
            style={{ marginBottom: 12 }}
          />
          <Text style={styles.emptyStateTitle}>No Tax Returns</Text>
          <Text style={styles.emptyStateSubtitle}>
            Your submitted returns will appear here.
          </Text>
        </Card>
      ) : (
        previousReturns.map((item) => (
          <Card key={item.return_id} style={styles.previousCard}>
            <View style={styles.previousRow}>
              <View style={styles.previousLeftSection}>
                <Ionicons
                  name="document-text"
                  size={24}
                  color="#C44736"
                  style={{ marginRight: 12 }}
                />
                <View>
                  <Text style={styles.previousYear}>{item.tax_year}</Text>
                  <Text style={styles.previousDate}>
                    Filed: {new Date(item.submitted_at).toLocaleDateString()}
                  </Text>
                </View>
              </View>

              <View style={styles.rightSection}>
                <View style={styles.greenBadge}>
                  <Text style={styles.badgeText}>Filed</Text>
                </View>

                <TouchableOpacity
                  style={styles.downloadButton}
                  onPress={() => handleDownload(item.tax_year.toString(), item.submitted_at)}
                >
                  <Ionicons
                    name="download-outline"
                    size={14}
                    color="#C44736"
                    style={{ marginRight: 4 }}
                  />
                  <Text style={styles.downloadText}>Download PDF</Text>
                </TouchableOpacity>
              </View>
            </View>
          </Card>
        ))
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 20,
    paddingTop: 55,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 28,
  },

  title: {
    fontSize: 34,
    color: "#111827",
    fontFamily: "Inter_700Bold",
    marginLeft: 10,
  },

  subtitle: {
    color: "#6B7280",
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    marginTop: -8,
    marginBottom: 28,
  },

  returnCard: {
    backgroundColor: "#C44736",
    borderRadius: 18,
    paddingVertical: 30,
    paddingHorizontal: 24,
    marginBottom: 16,
  },

  returnHeader: {
    flexDirection: "row",
    alignItems: "center",
  },

  returnIcon: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "rgba(255,255,255,0.18)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 18,
  },

  taxYear: {
    color: "#FDECEC",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },

  returnTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontFamily: "Inter_700Bold",
    marginVertical: 6,
  },

  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
  },

  statusBadge: {
    backgroundColor: "#FCE8E6",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },

  statusText: {
    color: "#C44736",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },

  dueDate: {
    color: "#FFFFFF",
    fontFamily: "Inter_400Regular",
  },

  fileButton: {
    backgroundColor: "#C44736",
    borderRadius: 16,
    paddingVertical: 20,
    alignItems: "center",
    marginBottom: 28,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 5,
  },

  fileButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "Inter_600SemiBold",
  },

  sectionLabel: {
    color: "#C44736",
    fontSize: 11,
    marginBottom: 12,
    fontFamily: "Inter_600SemiBold",
  },

  stepsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#ECECEC",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 2,
  },

  stepRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
  },

  stepDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    paddingBottom: 18,
    marginBottom: 8,
  },

  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#E5E7EB",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },

  completedCircle: {
    backgroundColor: "#34A853",
  },

  stepNumber: {
    color: "#6B7280",
    fontFamily: "Inter_600SemiBold",
  },

  stepTitle: {
    flex: 1,
    color: "#111827",
    fontFamily: "Inter_500Medium",
  },

  greenBadge: {
    backgroundColor: "#DFF5E7",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },

  badgeText: {
    color: "#34A853",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },

  grayBadge: {
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },

  grayBadgeText: {
    color: "#6B7280",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },

  previousCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#ECECEC",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 2,
  },

  previousRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },

  previousLeftSection: {
    flexDirection: "row",
    alignItems: "center",
  },

  previousYear: {
    color: "#111827",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
  },

  previousDate: {
    color: "#6B7280",
    marginTop: 4,
    fontSize: 12,
  },

  rightSection: {
    alignItems: "flex-end",
  },

  downloadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF5F3",
    borderWidth: 1,
    borderColor: "#F3C5BE",
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    marginTop: 10,
  },

  downloadText: {
    color: "#C44736",
    fontFamily: "Inter_500Medium",
    fontSize: 12,
  },

  emptyStateCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ECECEC",
  },

  emptyStateTitle: {
    fontSize: 16,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
    marginBottom: 4,
  },

  emptyStateSubtitle: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "#6B7280",
    textAlign: "center",
  },
});