spring.application.name=api

# Database Configuration
# Assess your local database with: psql -h localhost -p 5432 -U username -d database_name
spring.datasource.url=jdbc:postgresql://localhost:5432/taxpadi_db
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Arkesel SMS Configuration
arkesel.api.key=your_arkesel_api_key
arkesel.sms.sender=TaxPadi

# JWT Configuration - generate with: openssl rand -base64 32(Yes it ends with =)
jwt.secret=your_base64_encoded_secret_key
jwt.reset-secret=your_base64_encoded_secret_key

#Logging
logging.level.org.springframework.security=DEBUG
