server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:8+dcGYS3}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

paystack:
  secret-key: ${PAYSTACK_SECRET_KEY:sk_test_your_key_here}
  base-url: https://api.paystack.co
  callback-url: ${APP_BASE_URL:http://localhost:8080}/api/payments/callback

tax:
  rate: 0.075

jwt:
  secret: ${JWT_SECRET:mySuperSecureJwtSecretKey1234567890}
  expiration: 86400000
